version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - 5432
  app:
    build:
      dockerfile: Dockerfile
    volumes: 
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db